apiVersion: batch/v1
kind: Job
metadata:
  name: binarybitops-demo-1ab7ca0
  namespace: binarybitops-demo
spec:
  backoffLimit: 0
  activeDeadlineSeconds: 120
  template:
    metadata:
      labels:
        app: binarybitops-demo
    spec:
      restartPolicy: Never
      automountServiceAccountToken: false
      imagePullSecrets:
        - name: ecr-pull-auth
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: app
          image: 445137568300.dkr.ecr.eu-north-1.amazonaws.com/binarybitops-demo@sha256:04aa23ef6cda03a51cd4cfde3699e414b482c89e6e7e5b153f371c2a6a523795
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              cpu: 250m
              memory: 128Mi
              ephemeral-storage: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
